import '@/styles/app.css';
import ThemeProvider from '@/components/theme-provider';
import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import AuthContextProvider from '@/context/auth-context';
import QueryProvider from '@/components/query-provider';

const inter = Inter({
	display: 'swap',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			className={inter.className}
		>
			<body>
				<QueryProvider>
					<AuthContextProvider>
						<ThemeProvider>
							<Toaster />
							{children}
						</ThemeProvider>
					</AuthContextProvider>
				</QueryProvider>
			</body>
		</html>
	);
}
