version: '3.8'

services:
    next:
        build: ./frontend
        container_name: nextjs_app
        environment:
            - NODE_ENV=production
        networks:
            - app-network
        expose:
            - '3000'
        restart: unless-stopped

    nginx:
        image: nginx:alpine
        container_name: nginx_proxy
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d
        depends_on:
            - next
        networks:
            - app-network
        restart: unless-stopped

networks:
    app-network:
        driver: bridge
