version: '3.8'

services:
    nextjs:
        build: './frontend'
        container_name: nextjs-app
        ports:
            - '3000:3000'
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: nginx-proxy
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt
        ports:
            - '80:80' # HTTP trafiği için port
            - '443:443' # HTTPS trafiği için port
        depends_on:
            - nextjs
        networks:
            - app-network

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt
        command: certonly --webroot --webroot-path=/var/www/certbot --email girayselcuk15@gmail.com --agree-tos --no-eff-email --staging -d bilenleresor.com -d www.bilenleresor.com

networks:
    app-network:
        driver: bridge
